services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    entrypoint:
      - hackathon-portal-api
    env_file:
      - .env
    networks:
      - portal_public
      - portal_private
    expose:
      - 8000 # api server
      - 8001 # management api server
    labels:
      traefik.enable: true
      traefik.docker.network: portal_public

      traefik.http.routers.portal_backend.rule: PathPrefix(`/api`)
      traefik.http.services.portal_backend.loadbalancer.server.port: 8000
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - prod

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - portal_public
    expose:
      - 3000
    labels:
      traefik.enable: true
      traefik.docker.network: portal_public

      traefik.http.routers.portal_frontend.rule: PathPrefix(`/`)
      traefik.http.services.portal_frontend.loadbalancer.server.port: 3000
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - prod

  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
    networks:
      - portal_public
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    profiles:
      - prod
