//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod appointment;
pub mod event;
pub mod event_role_assignment;
pub mod project;
pub mod project_preference;
pub mod sea_orm_active_enums;
pub mod sidequest;
pub mod sidequest_attempt;
pub mod sidequest_score;
pub mod team;
pub mod team_role_assignment;
pub mod user;
