//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::appointment::Entity as Appointment;
pub use super::event::Entity as Event;
pub use super::event_role_assignment::Entity as EventRoleAssignment;
pub use super::project::Entity as Project;
pub use super::project_preference::Entity as ProjectPreference;
pub use super::sidequest::Entity as Sidequest;
pub use super::sidequest_attempt::Entity as SidequestAttempt;
pub use super::sidequest_score::Entity as SidequestScore;
pub use super::team::Entity as Team;
pub use super::team_role_assignment::Entity as TeamRoleAssignment;
pub use super::user::Entity as User;
