//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use super::sea_orm_active_enums::EventPhase;
use super::sea_orm_active_enums::EventVisibility;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub start: DateTime,
    pub end: DateTime,
    pub max_team_size: i32,
    pub is_read_only: bool,
    pub is_feedback_visible: bool,
    pub visibility: EventVisibility,
    pub phase: EventPhase,
    pub sidequest_cooldown: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub documentation_content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub welcome_content: Option<String>,
    pub max_teams_per_project: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::appointment::Entity")]
    Appointment,
    #[sea_orm(has_many = "super::event_role_assignment::Entity")]
    EventRoleAssignment,
    #[sea_orm(has_many = "super::project::Entity")]
    Project,
    #[sea_orm(has_many = "super::sidequest::Entity")]
    Sidequest,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
}

impl Related<super::appointment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointment.def()
    }
}

impl Related<super::event_role_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRoleAssignment.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::sidequest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sidequest.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
