//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::{Database, DbConn};

pub mod prelude;

pub mod appointment;
pub mod event;
pub mod event_role_assignment;
pub mod project;
pub mod project_preference;
pub mod sea_orm_active_enums;
pub mod sidequest;
pub mod sidequest_attempt;
pub mod sidequest_score;
pub mod team;
pub mod team_role_assignment;
pub mod user;

pub use crate::RepositoryResult;

pub use sea_orm::DbErr;

#[derive(Clone)]
pub struct DbRepository {
    conn: DbConn,
}

impl DbRepository {
    pub fn new(conn: DbConn) -> Self {
        Self { conn }
    }

    pub async fn from_url(url: &str) -> RepositoryResult<Self> {
        let result = Self {
            conn: Database::connect(url).await.unwrap(),
        };

        Ok(result)
    }

    pub fn conn(&self) -> &DbConn {
        &self.conn
    }
}
