//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    strum :: VariantArray,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_phase")]
pub enum EventPhase {
    #[sea_orm(string_value = "REGISTRATION")]
    Registration,
    #[sea_orm(string_value = "HACKING")]
    Hacking,
    #[sea_orm(string_value = "GRADING")]
    Grading,
    #[sea_orm(string_value = "FINISHED")]
    Finished,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    strum :: VariantArray,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_role")]
pub enum EventRole {
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
    #[sea_orm(string_value = "STAKEHOLDER")]
    Stakeholder,
    #[sea_orm(string_value = "PARTICIPANT")]
    Participant,
    #[sea_orm(string_value = "SIDEQUEST_MASTER")]
    SidequestMaster,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    strum :: VariantArray,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_visibility")]
pub enum EventVisibility {
    #[sea_orm(string_value = "HIDDEN")]
    Hidden,
    #[sea_orm(string_value = "INTERNAL")]
    Internal,
    #[sea_orm(string_value = "PUBLIC")]
    Public,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    strum :: VariantArray,
    utoipa :: ToSchema,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "expert_rating_category"
)]
pub enum ExpertRatingCategory {
    #[sea_orm(string_value = "FUNCTIONALITY")]
    Functionality,
    #[sea_orm(string_value = "UX")]
    Ux,
    #[sea_orm(string_value = "PRESENTATION")]
    Presentation,
}

impl ExpertRatingCategory {
    #[must_use]
    pub const fn get_weight(&self) -> f64 {
        match self {
            Self::Functionality => 0.5,
            Self::Ux => 0.3,
            Self::Presentation => 0.2,
        }
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_usage")]
pub enum MediaUsage {
    #[sea_orm(string_value = "TEAM_PHOTO")]
    TeamPhoto,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Copy,
    Hash,
    strum :: Display,
    strum :: VariantArray,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "team_role")]
pub enum TeamRole {
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
    #[sea_orm(string_value = "MEMBER")]
    Member,
}
