//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_phase")]
pub enum EventPhase {
    #[sea_orm(string_value = "GRADING")]
    Grading,
    #[sea_orm(string_value = "HACKING")]
    Hacking,
    #[sea_orm(string_value = "READONLY")]
    Readonly,
    #[sea_orm(string_value = "REGISTRATION")]
    Registration,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_role")]
pub enum EventRole {
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
    #[sea_orm(string_value = "PARTICIPANT")]
    Participant,
    #[sea_orm(string_value = "SIDEQUEST_MASTER")]
    SidequestMaster,
    #[sea_orm(string_value = "STAKEHOLDER")]
    Stakeholder,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_visibility")]
pub enum EventVisibility {
    #[sea_orm(string_value = "PRIVATE")]
    Private,
    #[sea_orm(string_value = "PUBLIC")]
    Public,
    #[sea_orm(string_value = "RESTRICTED")]
    Restricted,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "team_role")]
pub enum TeamRole {
    #[sea_orm(string_value = "MEMBER")]
    Member,
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
}
