//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
    Copy,
    strum::Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_phase")]
pub enum EventPhase {
    #[sea_orm(string_value = "FINISHED")]
    Finished,
    #[sea_orm(string_value = "GRADING")]
    Grading,
    #[sea_orm(string_value = "HACKING")]
    Hacking,
    #[sea_orm(string_value = "REGISTRATION")]
    Registration,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
    Copy,
    strum::Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_role")]
pub enum EventRole {
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
    #[sea_orm(string_value = "PARTICIPANT")]
    Participant,
    #[sea_orm(string_value = "SIDEQUEST_MASTER")]
    SidequestMaster,
    #[sea_orm(string_value = "STAKEHOLDER")]
    Stakeholder,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
    Copy,
    strum::Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_visibility")]
pub enum EventVisibility {
    #[sea_orm(string_value = "HIDDEN")]
    Hidden,
    #[sea_orm(string_value = "INTERNAL")]
    Internal,
    #[sea_orm(string_value = "PUBLIC")]
    Public,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
    Copy,
    strum::Display,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "expert_rating_category"
)]
pub enum ExpertRatingCategory {
    #[sea_orm(string_value = "FUNCTIONALITY")]
    Functionality,
    #[sea_orm(string_value = "UX")]
    Ux,
    #[sea_orm(string_value = "PRESENTATION")]
    Presentation,
}

impl ExpertRatingCategory {
    pub fn get_weight(&self) -> f64 {
        match self {
            ExpertRatingCategory::Functionality => 0.5,
            ExpertRatingCategory::Ux => 0.3,
            ExpertRatingCategory::Presentation => 0.2,
        }
    }
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa::ToSchema,
    Hash,
    Copy,
    strum::Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "team_role")]
pub enum TeamRole {
    #[sea_orm(string_value = "MEMBER")]
    Member,
    #[sea_orm(string_value = "MENTOR")]
    Mentor,
}
