//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub project_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    pub index: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EventId",
        to = "super::event::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Event,
    #[sea_orm(has_many = "super::expert_rating::Entity")]
    ExpertRating,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Project,
    #[sea_orm(has_many = "super::project_preference::Entity")]
    ProjectPreference,
    #[sea_orm(has_many = "super::sidequest_score::Entity")]
    SidequestScore,
    #[sea_orm(has_many = "super::team_role_assignment::Entity")]
    TeamRoleAssignment,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::expert_rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpertRating.def()
    }
}

impl Related<super::project_preference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPreference.def()
    }
}

impl Related<super::sidequest_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SidequestScore.def()
    }
}

impl Related<super::team_role_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamRoleAssignment.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_preference::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_preference::Relation::Team.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
