//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub auth_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_role_assignment::Entity")]
    EventRoleAssignment,
    #[sea_orm(has_many = "super::expert_rating::Entity")]
    ExpertRating,
    #[sea_orm(has_many = "super::sidequest_attempt::Entity")]
    SidequestAttempt,
    #[sea_orm(has_many = "super::team_role_assignment::Entity")]
    TeamRoleAssignment,
    #[sea_orm(has_many = "super::upload::Entity")]
    Upload,
}

impl Related<super::event_role_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventRoleAssignment.def()
    }
}

impl Related<super::expert_rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpertRating.def()
    }
}

impl Related<super::sidequest_attempt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SidequestAttempt.def()
    }
}

impl Related<super::team_role_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamRoleAssignment.def()
    }
}

impl Related<super::upload::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Upload.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
