//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_assignment::Entity")]
    ProjectAssignment,
    #[sea_orm(has_many = "super::project_preference::Entity")]
    ProjectPreference,
}

impl Related<super::project_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectAssignment.def()
    }
}

impl Related<super::project_preference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPreference.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
