//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_assignment::Entity")]
    ProjectAssignment,
    #[sea_orm(has_many = "super::project_preference::Entity")]
    ProjectPreference,
    #[sea_orm(has_many = "super::team_member::Entity")]
    TeamMember,
    #[sea_orm(has_many = "super::team_score::Entity")]
    TeamScore,
}

impl Related<super::project_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectAssignment.def()
    }
}

impl Related<super::project_preference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPreference.def()
    }
}

impl Related<super::team_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamMember.def()
    }
}

impl Related<super::team_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamScore.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::team_member::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::team_member::Relation::Team.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
