//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[schema(as=DbUser::Model)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub auth_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_assignment::Entity")]
    RoleAssignment,
    #[sea_orm(has_many = "super::sidequest_attempt::Entity")]
    SidequestAttempt,
    #[sea_orm(has_many = "super::team_member::Entity")]
    TeamMember,
}

impl Related<super::role_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleAssignment.def()
    }
}

impl Related<super::sidequest_attempt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SidequestAttempt.def()
    }
}

impl Related<super::team_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamMember.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        super::team_member::Relation::Team.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::team_member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
